import { Deal, BlogPost } from './types';

export const CATEGORIES: string[] = ['Creams', 'Cleansers', 'Serums', 'Sun Protection', 'Exfoliators'];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: 'The Ultimate Guide to Hyaluronic Acid',
    excerpt: 'Discover why this powerhouse ingredient is a must-have in your skincare routine for hydrated, plump skin.',
    imageUrl: 'https://images.unsplash.com/photo-1608729591152-3a388f4b26da?q=80&w=600&h=400&auto=format&fit=crop',
    link: '#',
  },
  {
    id: 2,
    title: 'Niacinamide: The Secret to a Brighter Complexion',
    excerpt: 'Learn how Niacinamide can transform your skin by tackling everything from pores to uneven skin tone.',
    imageUrl: 'https://images.unsplash.com/photo-1557852643-a757b4a16518?q=80&w=600&h=400&auto=format&fit=crop',
    link: '#',
  },
  {
    id: 3,
    title: 'SPF Explained: Everything You Need to Know',
    excerpt: 'Sunscreen is non-negotiable. We break down the difference between mineral and chemical sunscreens.',
    imageUrl: 'https://images.unsplash.com/photo-1556912922-64abb5d39e29?q=80&w=600&h=400&auto=format&fit=crop',
    link: '#',
  },
];

export const DEALS: Deal[] = [
    {
        id: 1,
        productName: 'CeraVe SA Smoothing Cleanser for Dry, Rough, Bumpy Skin',
        brand: 'CeraVe',
        category: 'Cleansers',
        imageUrl: 'https://images-cdn.ubuy.co.in/633b23a238964345ea5f4581-cerave-sa-smoothing-cleanser-for-dry.jpg',
        originalPrice: 15.00,
        discountedPrice: 10.50,
        discountPercentage: 30,
        retailer: 'Boots',
        affiliateUrl: '#',
        description: 'A gentle salicylic acid cleanser can help exfoliate and smooth your skin while also effectively removing oil and dirt, sweeping away dead cells, and softening rough skin—without leaving skin feeling dry.',
    },
    {
        id: 2,
        productName: 'La Roche-Posay Anthelios UVMUNE 400 Invisible Fluid SPF50+',
        brand: 'La Roche-Posay',
        category: 'Sun Protection',
        imageUrl: 'https://images.unineed.com/media/catalog/product/cache/4157743d80d27622c6087a274570c99f/l/a/la_roche_posay_anthelios_uvmune_400_invisible_fluid_spf50_sun_cream_50ml.jpg',
        originalPrice: 20.00,
        discountedPrice: 15.00,
        discountPercentage: 25,
        retailer: 'Lookfantastic',
        affiliateUrl: '#',
        description: 'A lightweight, invisible fluid that offers the highest UVA/UVB protection for all skin types, even the most sensitive.',
    },
    {
        id: 3,
        productName: 'The Ordinary Niacinamide 10% + Zinc 1%',
        brand: 'The Ordinary',
        category: 'Serums',
        imageUrl: 'https://images.ctfassets.net/jdgtuh2q0s1k/58L3v21a21CAm2a8CSm82k/883a2c53d085a66a1e36f019a3b2b8e3/The-Ordinary-Niacinamide-10-Zinc-1-30ml-PDP-2-1200x1200.jpg',
        originalPrice: 5.60,
        discountedPrice: 4.90,
        discountPercentage: 13,
        retailer: 'Cult Beauty',
        affiliateUrl: '#',
        description: 'A high-strength vitamin and mineral blemish formula that helps to reduce the appearance of skin blemishes and congestion.',
    },
    {
        id: 4,
        productName: 'Glow Recipe Watermelon Glow PHA + BHA Pore-Tight Toner',
        brand: 'Glow Recipe',
        category: 'Exfoliators',
        imageUrl: 'https://cdn.shopify.com/s/files/1/0157/7858/files/PDP-Watermelon-Toner-150ml_1_1500x.jpg?v=1684949176',
        originalPrice: 31.00,
        discountedPrice: 24.80,
        discountPercentage: 20,
        retailer: 'Cult Beauty',
        affiliateUrl: '#',
        description: 'Hydrate skin and tighten pores at once with the ultra-gentle Watermelon Glow PHA + BHA Pore-Tight Toner for supple, smooth skin.',
    },
    {
        id: 5,
        productName: 'Kiehl\'s Ultra Facial Cream with Squalane',
        brand: 'Kiehl\'s',
        category: 'Creams',
        imageUrl: 'https://www.kiehls.co.uk/dw/image/v2/AAQP_PRD/on/demandware.static/-/Sites-kiehls-master-catalog/default/dw204b341f/2022-FRAGRANCE-FREE/ULTRA-FACIAL-CREAM-50ML-3605972746726-FRONT.jpg?sw=1200&sh=1200&sm=fit&q=70',
        originalPrice: 30.00,
        discountedPrice: 25.50,
        discountPercentage: 15,
        retailer: 'Boots',
        affiliateUrl: '#',
        description: 'Our #1 facial cream has a unique lightweight texture and lasting 24-hour hydration to leave skin softer, smoother and visibly healthier.',
    },
    {
        id: 6,
        productName: 'Paula\'s Choice SKIN PERFECTING 2% BHA Liquid Exfoliant',
        brand: 'Paula\'s Choice',
        category: 'Exfoliators',
        imageUrl: 'https://cdn.shopify.com/s/files/1/0088/6663/7297/products/BHA_Liquid_Exfoliant_US_1200x.jpg?v=1678822066',
        originalPrice: 34.00,
        discountedPrice: 27.20,
        discountPercentage: 20,
        retailer: 'Cult Beauty',
        affiliateUrl: '#',
        description: 'A gentle, leave-on exfoliant with salicylic acid that quickly unclogs pores, smooths wrinkles, and brightens and evens out skin tone.',
    },
];
